// <auto-generated />
using System;
using APIs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace APIs.Migrations
{
    [DbContext(typeof(CareerHubDbContext))]
    partial class CareerHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("APIs.Models.Applicant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("applicants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-0000-0000-0000-000000000001"),
                            Email = "thabo.nkosi@example.com",
                            FirstName = "Thabo",
                            LastName = "Nkosi",
                            Phone = "0810000001"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0000-0000-0000-000000000002"),
                            Email = "amanda.vandermerwe@example.com",
                            FirstName = "Amanda",
                            LastName = "van der Merwe",
                            Phone = "0810000002"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0000-0000-0000-000000000003"),
                            Email = "sipho.dlamini@example.com",
                            FirstName = "Sipho",
                            LastName = "Dlamini",
                            Phone = "0810000003"
                        });
                });

            modelBuilder.Entity("APIs.Models.Application", b =>
                {
                    b.Property<Guid>("JobListingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("AvailableImmediately")
                        .HasColumnType("boolean");

                    b.Property<string>("CoverLetter")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("NoticePeriodWeeks")
                        .HasColumnType("integer");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("integer");

                    b.HasKey("JobListingId", "ApplicantId");

                    b.HasIndex("ApplicantId");

                    b.ToTable("applications", (string)null);

                    b.HasData(
                        new
                        {
                            JobListingId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            ApplicantId = new Guid("bbbbbbbb-0000-0000-0000-000000000001"),
                            AvailableImmediately = true,
                            CoverLetter = "I am excited to apply for this role and believe my experience aligns well with what you're looking for.",
                            Email = "thabo.nkosi@example.com",
                            FullName = "Thabo Nkosi",
                            NoticePeriodWeeks = 0,
                            Phone = "0810000000",
                            Status = 0,
                            SubmittedAt = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            YearsOfExperience = 2
                        },
                        new
                        {
                            JobListingId = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            ApplicantId = new Guid("bbbbbbbb-0000-0000-0000-000000000001"),
                            AvailableImmediately = true,
                            CoverLetter = "I am excited to apply for this role and believe my experience aligns well with what you're looking for.",
                            Email = "thabo.nkosi@example.com",
                            FullName = "Thabo Nkosi",
                            NoticePeriodWeeks = 0,
                            Phone = "0810000000",
                            Status = 1,
                            SubmittedAt = new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            YearsOfExperience = 2
                        },
                        new
                        {
                            JobListingId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            ApplicantId = new Guid("bbbbbbbb-0000-0000-0000-000000000001"),
                            AvailableImmediately = true,
                            CoverLetter = "I am excited to apply for this role and believe my experience aligns well with what you're looking for.",
                            Email = "thabo.nkosi@example.com",
                            FullName = "Thabo Nkosi",
                            NoticePeriodWeeks = 0,
                            Phone = "0810000000",
                            Status = 2,
                            SubmittedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            YearsOfExperience = 2
                        },
                        new
                        {
                            JobListingId = new Guid("d4e5f6a7-b8c9-0123-defa-234567890123"),
                            ApplicantId = new Guid("bbbbbbbb-0000-0000-0000-000000000001"),
                            AvailableImmediately = true,
                            CoverLetter = "I am excited to apply for this role and believe my experience aligns well with what you're looking for.",
                            Email = "thabo.nkosi@example.com",
                            FullName = "Thabo Nkosi",
                            NoticePeriodWeeks = 0,
                            Phone = "0810000000",
                            Status = 3,
                            SubmittedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            YearsOfExperience = 2
                        },
                        new
                        {
                            JobListingId = new Guid("e5f6a7b8-c9d0-1234-efab-345678901234"),
                            ApplicantId = new Guid("bbbbbbbb-0000-0000-0000-000000000001"),
                            AvailableImmediately = true,
                            CoverLetter = "I am excited to apply for this role and believe my experience aligns well with what you're looking for.",
                            Email = "thabo.nkosi@example.com",
                            FullName = "Thabo Nkosi",
                            NoticePeriodWeeks = 0,
                            Phone = "0810000000",
                            Status = 4,
                            SubmittedAt = new DateTime(2026, 7, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            YearsOfExperience = 2
                        },
                        new
                        {
                            JobListingId = new Guid("f6a7b8c9-d0e1-2345-fabc-456789012345"),
                            ApplicantId = new Guid("bbbbbbbb-0000-0000-0000-000000000001"),
                            AvailableImmediately = true,
                            CoverLetter = "I am excited to apply for this role and believe my experience aligns well with what you're looking for.",
                            Email = "thabo.nkosi@example.com",
                            FullName = "Thabo Nkosi",
                            NoticePeriodWeeks = 0,
                            Phone = "0810000000",
                            Status = 0,
                            SubmittedAt = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            YearsOfExperience = 2
                        },
                        new
                        {
                            JobListingId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            ApplicantId = new Guid("bbbbbbbb-0000-0000-0000-000000000002"),
                            AvailableImmediately = false,
                            CoverLetter = "I am excited to apply for this role and believe my experience aligns well with what you're looking for.",
                            Email = "amanda.vandermerwe@example.com",
                            FullName = "Amanda van der Merwe",
                            NoticePeriodWeeks = 4,
                            Phone = "0810000000",
                            Status = 1,
                            SubmittedAt = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            YearsOfExperience = 4
                        },
                        new
                        {
                            JobListingId = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            ApplicantId = new Guid("bbbbbbbb-0000-0000-0000-000000000002"),
                            AvailableImmediately = false,
                            CoverLetter = "I am excited to apply for this role and believe my experience aligns well with what you're looking for.",
                            Email = "amanda.vandermerwe@example.com",
                            FullName = "Amanda van der Merwe",
                            NoticePeriodWeeks = 4,
                            Phone = "0810000000",
                            Status = 2,
                            SubmittedAt = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            YearsOfExperience = 4
                        },
                        new
                        {
                            JobListingId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            ApplicantId = new Guid("bbbbbbbb-0000-0000-0000-000000000002"),
                            AvailableImmediately = false,
                            CoverLetter = "I am excited to apply for this role and believe my experience aligns well with what you're looking for.",
                            Email = "amanda.vandermerwe@example.com",
                            FullName = "Amanda van der Merwe",
                            NoticePeriodWeeks = 4,
                            Phone = "0810000000",
                            Status = 3,
                            SubmittedAt = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            YearsOfExperience = 4
                        },
                        new
                        {
                            JobListingId = new Guid("d4e5f6a7-b8c9-0123-defa-234567890123"),
                            ApplicantId = new Guid("bbbbbbbb-0000-0000-0000-000000000002"),
                            AvailableImmediately = false,
                            CoverLetter = "I am excited to apply for this role and believe my experience aligns well with what you're looking for.",
                            Email = "amanda.vandermerwe@example.com",
                            FullName = "Amanda van der Merwe",
                            NoticePeriodWeeks = 4,
                            Phone = "0810000000",
                            Status = 4,
                            SubmittedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            YearsOfExperience = 4
                        },
                        new
                        {
                            JobListingId = new Guid("e5f6a7b8-c9d0-1234-efab-345678901234"),
                            ApplicantId = new Guid("bbbbbbbb-0000-0000-0000-000000000002"),
                            AvailableImmediately = false,
                            CoverLetter = "I am excited to apply for this role and believe my experience aligns well with what you're looking for.",
                            Email = "amanda.vandermerwe@example.com",
                            FullName = "Amanda van der Merwe",
                            NoticePeriodWeeks = 4,
                            Phone = "0810000000",
                            Status = 0,
                            SubmittedAt = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            YearsOfExperience = 4
                        },
                        new
                        {
                            JobListingId = new Guid("f6a7b8c9-d0e1-2345-fabc-456789012345"),
                            ApplicantId = new Guid("bbbbbbbb-0000-0000-0000-000000000002"),
                            AvailableImmediately = false,
                            CoverLetter = "I am excited to apply for this role and believe my experience aligns well with what you're looking for.",
                            Email = "amanda.vandermerwe@example.com",
                            FullName = "Amanda van der Merwe",
                            NoticePeriodWeeks = 4,
                            Phone = "0810000000",
                            Status = 1,
                            SubmittedAt = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            YearsOfExperience = 4
                        },
                        new
                        {
                            JobListingId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            ApplicantId = new Guid("bbbbbbbb-0000-0000-0000-000000000003"),
                            AvailableImmediately = true,
                            CoverLetter = "I am excited to apply for this role and believe my experience aligns well with what you're looking for.",
                            Email = "sipho.dlamini@example.com",
                            FullName = "Sipho Dlamini",
                            NoticePeriodWeeks = 0,
                            Phone = "0810000000",
                            Status = 2,
                            SubmittedAt = new DateTime(2026, 6, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            YearsOfExperience = 6
                        },
                        new
                        {
                            JobListingId = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            ApplicantId = new Guid("bbbbbbbb-0000-0000-0000-000000000003"),
                            AvailableImmediately = true,
                            CoverLetter = "I am excited to apply for this role and believe my experience aligns well with what you're looking for.",
                            Email = "sipho.dlamini@example.com",
                            FullName = "Sipho Dlamini",
                            NoticePeriodWeeks = 0,
                            Phone = "0810000000",
                            Status = 3,
                            SubmittedAt = new DateTime(2026, 6, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            YearsOfExperience = 6
                        },
                        new
                        {
                            JobListingId = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            ApplicantId = new Guid("bbbbbbbb-0000-0000-0000-000000000003"),
                            AvailableImmediately = true,
                            CoverLetter = "I am excited to apply for this role and believe my experience aligns well with what you're looking for.",
                            Email = "sipho.dlamini@example.com",
                            FullName = "Sipho Dlamini",
                            NoticePeriodWeeks = 0,
                            Phone = "0810000000",
                            Status = 4,
                            SubmittedAt = new DateTime(2026, 6, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            YearsOfExperience = 6
                        },
                        new
                        {
                            JobListingId = new Guid("d4e5f6a7-b8c9-0123-defa-234567890123"),
                            ApplicantId = new Guid("bbbbbbbb-0000-0000-0000-000000000003"),
                            AvailableImmediately = true,
                            CoverLetter = "I am excited to apply for this role and believe my experience aligns well with what you're looking for.",
                            Email = "sipho.dlamini@example.com",
                            FullName = "Sipho Dlamini",
                            NoticePeriodWeeks = 0,
                            Phone = "0810000000",
                            Status = 0,
                            SubmittedAt = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            YearsOfExperience = 6
                        },
                        new
                        {
                            JobListingId = new Guid("e5f6a7b8-c9d0-1234-efab-345678901234"),
                            ApplicantId = new Guid("bbbbbbbb-0000-0000-0000-000000000003"),
                            AvailableImmediately = true,
                            CoverLetter = "I am excited to apply for this role and believe my experience aligns well with what you're looking for.",
                            Email = "sipho.dlamini@example.com",
                            FullName = "Sipho Dlamini",
                            NoticePeriodWeeks = 0,
                            Phone = "0810000000",
                            Status = 1,
                            SubmittedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            YearsOfExperience = 6
                        },
                        new
                        {
                            JobListingId = new Guid("f6a7b8c9-d0e1-2345-fabc-456789012345"),
                            ApplicantId = new Guid("bbbbbbbb-0000-0000-0000-000000000003"),
                            AvailableImmediately = true,
                            CoverLetter = "I am excited to apply for this role and believe my experience aligns well with what you're looking for.",
                            Email = "sipho.dlamini@example.com",
                            FullName = "Sipho Dlamini",
                            NoticePeriodWeeks = 0,
                            Phone = "0810000000",
                            Status = 2,
                            SubmittedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            YearsOfExperience = 6
                        });
                });

            modelBuilder.Entity("APIs.Models.Company", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("CompanyId");

                    b.ToTable("companies", (string)null);

                    b.HasData(
                        new
                        {
                            CompanyId = new Guid("aaaaaaaa-0000-0000-0000-000000000001"),
                            CompanyName = "Takealot",
                            Industry = "Technology"
                        },
                        new
                        {
                            CompanyId = new Guid("aaaaaaaa-0000-0000-0000-000000000002"),
                            CompanyName = "Vodacom",
                            Industry = "Telecommunications"
                        },
                        new
                        {
                            CompanyId = new Guid("aaaaaaaa-0000-0000-0000-000000000003"),
                            CompanyName = "Discovery",
                            Industry = "Insurance"
                        },
                        new
                        {
                            CompanyId = new Guid("aaaaaaaa-0000-0000-0000-000000000004"),
                            CompanyName = "Standard Bank",
                            Industry = "Finance"
                        },
                        new
                        {
                            CompanyId = new Guid("aaaaaaaa-0000-0000-0000-000000000005"),
                            CompanyName = "FNB FirstRand",
                            Industry = "Finance"
                        },
                        new
                        {
                            CompanyId = new Guid("aaaaaaaa-0000-0000-0000-000000000006"),
                            CompanyName = "Media24",
                            Industry = "Media"
                        });
                });

            modelBuilder.Entity("APIs.Models.JobListing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ClosingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("SalaryMax")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SalaryMin")
                        .HasColumnType("numeric");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .HasColumnType("tsvector");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Title", "CompanyId")
                        .IsUnique();

                    b.ToTable("job_listings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            ClosingDate = new DateTime(2026, 7, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompanyId = new Guid("aaaaaaaa-0000-0000-0000-000000000001"),
                            Description = "We are looking for a talented Senior Frontend Engineer...",
                            EmploymentType = "FullTime",
                            IsActive = true,
                            Location = "Cape Town",
                            PostedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            SalaryMax = 45000m,
                            SalaryMin = 30000m,
                            Title = "Senior Frontend Software Engineer"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            ClosingDate = new DateTime(2026, 7, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompanyId = new Guid("aaaaaaaa-0000-0000-0000-000000000002"),
                            Description = "We are looking for a Junior Systems Developer...",
                            EmploymentType = "FullTime",
                            IsActive = true,
                            Location = "Johannesburg, Sandton",
                            PostedAt = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            SalaryMax = 30000m,
                            SalaryMin = 15000m,
                            Title = "Junior Systems Developer"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            ClosingDate = new DateTime(2026, 7, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompanyId = new Guid("aaaaaaaa-0000-0000-0000-000000000003"),
                            Description = "We are looking for a creative UX/Web Designer...",
                            EmploymentType = "Contract",
                            IsActive = true,
                            Location = "Sandton",
                            PostedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            SalaryMax = 18000m,
                            SalaryMin = 10000m,
                            Title = "UX/Web Designer"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-0123-defa-234567890123"),
                            ClosingDate = new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompanyId = new Guid("aaaaaaaa-0000-0000-0000-000000000004"),
                            Description = "We are looking for a Data Analyst Intern...",
                            EmploymentType = "Internship",
                            IsActive = false,
                            Location = "Pretoria/Hybrid",
                            PostedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            SalaryMax = 22000m,
                            SalaryMin = 15000m,
                            Title = "Data Analyst Intern"
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-c9d0-1234-efab-345678901234"),
                            ClosingDate = new DateTime(2026, 7, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompanyId = new Guid("aaaaaaaa-0000-0000-0000-000000000005"),
                            Description = "We are looking for a Senior DevOps Engineer...",
                            EmploymentType = "FullTime",
                            IsActive = true,
                            Location = "Bloemfontein",
                            PostedAt = new DateTime(2026, 6, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            SalaryMax = 110000m,
                            SalaryMin = 70000m,
                            Title = "Senior DevOps Engineer"
                        },
                        new
                        {
                            Id = new Guid("f6a7b8c9-d0e1-2345-fabc-456789012345"),
                            ClosingDate = new DateTime(2026, 7, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompanyId = new Guid("aaaaaaaa-0000-0000-0000-000000000006"),
                            Description = "We are looking for a Content Writer...",
                            EmploymentType = "PartTime",
                            IsActive = true,
                            Location = "Remote",
                            PostedAt = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            SalaryMax = 18000m,
                            SalaryMin = 12000m,
                            Title = "Part-Time Content Writer/Promoter"
                        });
                });

            modelBuilder.Entity("APIs.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("APIs.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 7, 22, 22, 6, 42, 352, DateTimeKind.Utc).AddTicks(5203),
                            Email = "admin@careerhub.co.za",
                            IsActive = true,
                            PasswordHash = "Admin123!",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 7, 22, 22, 6, 42, 353, DateTimeKind.Utc).AddTicks(4395),
                            Email = "employer@careerhub.co.za",
                            IsActive = true,
                            PasswordHash = "Employer123!",
                            Role = "Employer",
                            Username = "employer"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 7, 22, 22, 6, 42, 353, DateTimeKind.Utc).AddTicks(4455),
                            Email = "applicant@careerhub.co.za",
                            IsActive = true,
                            PasswordHash = "Applicant123!",
                            Role = "Applicant",
                            Username = "applicant"
                        });
                });

            modelBuilder.Entity("APIs.Models.Application", b =>
                {
                    b.HasOne("APIs.Models.Applicant", "Applicant")
                        .WithMany("Applications")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIs.Models.JobListing", "JobListing")
                        .WithMany("Applications")
                        .HasForeignKey("JobListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("JobListing");
                });

            modelBuilder.Entity("APIs.Models.JobListing", b =>
                {
                    b.HasOne("APIs.Models.Company", "Company")
                        .WithMany("JobListings")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("APIs.Models.RefreshToken", b =>
                {
                    b.HasOne("APIs.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("APIs.Models.Applicant", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("APIs.Models.Company", b =>
                {
                    b.Navigation("JobListings");
                });

            modelBuilder.Entity("APIs.Models.JobListing", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("APIs.Models.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
