name: CareerHub API Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and testing environment
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code Repository Actions
      uses: actions/checkout@v4

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'
        cache: true

    - name: Restore App Dependencies
      run: dotnet restore

    - name: Build Solution without Restore
      run: dotnet build --no-restore --configuration Release

    - name: Run Testing (Unit, Integration & Repository)
      run: dotnet test --no-build --configuration Release --verbosity normal